"""Add basic role

Revision ID: eef6965fa881
Revises: 7ec4380c7c1a
Create Date: 2026-01-06 22:05:55.432185

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eef6965fa881"
down_revision: Union[str, Sequence[str], None] = "7ec4380c7c1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO role (name) VALUES ('admin')")
    op.execute("INSERT INTO role (name) VALUES ('user')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM role WHERE name = 'admin'")
    op.execute("DELETE FROM role WHERE name = 'user'")
    # ### end Alembic commands ###
