class ErrorCode:
    # Auth Errors
    AUTH_EMAIL_ALREADY_EXISTS = "AUTH-001"
    AUTH_INVALID_CREDENTIALS = "AUTH-002"
    AUTH_INACTIVE_USER = "AUTH-003"
    AUTH_USER_NOT_FOUND = "AUTH-004"
    AUTH_ROLE_NOT_FOUND = "AUTH-005"

    # Generic Errors
    INTERNAL_SERVER_ERROR = "INTERNAL-500"
    VALIDATION_ERROR = "VALIDATION-422"
